Modified from Origin PyTorch Pocket Reference.
Written by: Joe Papa. PUBLISHED BY: O'Reilly Media, Inc.
https://learning.oreilly.com/library/view/pytorch-pocket-reference/9781492089995/

In [ ]:
import torch
x= torch.tensor([[1,2,3],[4,5,6]])
y= torch.tensor([[4,5,6],[9,11,33]])

z = x +y

print(z)

print(z.size())

tensor([[ 5,  7,  9],
        [13, 16, 39]])
torch.Size([2, 3])


In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x= torch.tensor([[1,2,3],[4,5,6]], device=device)
y= torch.tensor([[4,5,6],[9,11,33]], device=device)

z = x + y

print(z)
print(z.size())
print(z.device)

tensor([[ 5,  7,  9],
        [13, 16, 39]])
torch.Size([2, 3])
cpu


In [ ]:
emptyw =  torch.empty(100,200)
print(emptyw)
print(emptyw.size())

tensor([[ 1.5835e-42,  4.3813e-41, -5.8920e+33,  ...,  4.3813e-41,
          0.0000e+00,  0.0000e+00],
        [ 1.0370e-43,  3.3418e-41, -5.8923e+33,  ...,  4.3813e-41,
          0.0000e+00,  0.0000e+00],
        [ 1.0510e-43,  4.3813e-41, -5.8928e+33,  ...,  3.3418e-41,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 1.7174e-28,  4.3813e-41,  2.8353e-31,  ...,  4.3814e-41,
          2.4990e-30,  4.3814e-41],
        [ 1.7172e-28,  4.3813e-41,  2.8352e-31,  ...,  4.3814e-41,
          2.8352e-31,  4.3814e-41],
        [ 2.4990e-30,  4.3814e-41,  1.7173e-28,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
torch.Size([100, 200])


In [ ]:
zeros_w = torch.zeros(100,200)
ones_w = torch.ones(100,200)
print(zeros_w)
print(ones_w)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])


In [ ]:
rand_w = torch.rand(10,20)
randn_w = torch.randn(10,20)
randint_w = torch.randint(0,5,(10,20))
print(rand_w)
print(f"randn: {randn_w}")
print(f"randint: {randint_w}")

tensor([[0.6082, 0.2804, 0.7306, 0.7030, 0.3951, 0.4991, 0.4846, 0.7773, 0.5862,
         0.8573, 0.5510, 0.1174, 0.8739, 0.2883, 0.0419, 0.9424, 0.4890, 0.0070,
         0.5059, 0.5304],
        [0.3878, 0.9011, 0.3300, 0.5406, 0.3367, 0.1422, 0.2321, 0.0219, 0.3456,
         0.3451, 0.1975, 0.9881, 0.3087, 0.9271, 0.4149, 0.3988, 0.6169, 0.9616,
         0.1827, 0.0217],
        [0.9264, 0.7756, 0.5797, 0.5455, 0.9101, 0.8823, 0.0088, 0.8787, 0.3238,
         0.2867, 0.6868, 0.8592, 0.4706, 0.1401, 0.5820, 0.0512, 0.6135, 0.7387,
         0.9830, 0.1236],
        [0.0522, 0.0617, 0.7258, 0.3967, 0.4798, 0.9188, 0.2581, 0.6042, 0.7335,
         0.0372, 0.5052, 0.4953, 0.4622, 0.0367, 0.5995, 0.0260, 0.5826, 0.8593,
         0.6319, 0.7157],
        [0.7230, 0.8893, 0.4540, 0.8878, 0.5156, 0.1702, 0.0898, 0.5809, 0.1753,
         0.5695, 0.9505, 0.1602, 0.2800, 0.3892, 0.9545, 0.4354, 0.9560, 0.3237,
         0.8254, 0.7612],
        [0.1842, 0.6956, 0.7884, 0.0531, 0.8708, 0.9383, 0.2

In [ ]:
comp1 = torch.empty((3,5), dtype=torch.float64, device="cpu")
clone_comp1 = torch.empty_like(comp1)
print(f"comp1:{comp1}")
print(f"empty_like clone:{clone_comp1}")

comp1:tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, 4.9407e-324],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, 1.9763e-323],
        [4.9407e-324, 1.7438e-309, 6.2811e-312, 2.4209e-322, 5.0607e-310]],
       dtype=torch.float64)
empty_like clone:tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, 4.9407e-324],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, 2.4209e-322],
        [4.9407e-324, 1.7438e-309, 6.2811e-312, 3.2114e-322, 5.0607e-310]],
       dtype=torch.float64)


In [ ]:
arangeTensor = torch.arange(start = 0,end=10,step=1) #what is the usage of this?
arangeTensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
linspaceT = torch.linspace(0,10,steps=100)
linspaceT

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4949,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00

In [ ]:
print(arangeTensor.ndim)
print(w.ndim)

1
2


In [ ]:
sample = torch.empty([10,5])
print(sample)

tensor([[3.1950e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.3563e-19],
        [1.3563e-19, 6.9636e+11, 4.4711e+21, 7.1221e+28, 1.1028e+21],
        [7.2065e+31, 2.0194e-19, 7.0062e+22, 4.1586e+21, 7.3995e+20],
        [1.8672e+25, 2.6217e+20, 8.3967e-33, 1.3563e-19, 1.3563e-19],
        [1.9026e+31, 4.4711e+21, 6.7816e+28, 7.2251e+28, 1.8758e-19],
        [3.6465e+12, 1.7476e-19, 3.1836e+06, 1.7979e-19, 3.3336e+03],
        [1.1692e-19, 1.3563e-19, 6.7161e+08, 8.7530e-04, 2.9560e+21],
        [7.3986e+20, 1.9421e+31, 1.8492e+20, 1.9069e-19, 7.3804e+28],
        [2.0115e-19, 2.0535e-19, 7.1850e+22, 4.2963e+24, 7.1345e+31],
        [6.8608e+22, 1.0832e+24, 1.8015e+25, 4.9643e+28, 7.1346e+31]])


In [ ]:
#creates a tensor of random numbers drawn from the Cauchy distribution.
cauchy_tensor = sample.cauchy_()  #in-place  methods use the underscore postfix
print(cauchy_tensor)

tensor([[-2.4660e+01, -8.4099e-01, -2.7996e+00, -9.0217e-01, -1.1751e+00],
        [-1.3282e-01,  3.7815e-01,  2.3475e-02, -5.7727e-01,  1.0330e+00],
        [-2.9110e+00, -2.5089e-01,  1.5478e-01,  3.9641e-01, -1.2381e+00],
        [ 6.7767e-01, -1.6637e-01, -4.2445e+00, -1.6311e+01, -9.1195e-01],
        [ 1.3366e-01,  4.7155e+00,  2.0769e-01, -1.7947e+00, -1.7459e+00],
        [ 3.1025e+00, -1.0786e+00,  1.9610e+00, -2.6433e-02, -2.0768e-01],
        [-3.3846e+00,  6.0997e-02, -1.3306e+01,  2.0803e-02,  2.5757e+00],
        [ 9.8136e+00, -1.0643e+00, -3.3920e-01, -6.6684e-01, -1.7135e+00],
        [-5.0636e-01, -6.1784e-02, -1.9064e+00,  4.0760e-01,  6.5306e-02],
        [-2.7340e+00, -4.0208e+00,  5.3922e-01, -3.9001e-01, -1.0223e+00]])


### Indexing, Slicing, Combining, and Splitting Tensors

In [ ]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

print(f"without .item():{x[1,1]}")

print(f"[1,1].item() : {x[1,1].item()}")


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
without .item():4
[1,1].item() : 4


In [ ]:
print(x.size())
print(x.shape)
print(x.ndim)

torch.Size([4, 2])
torch.Size([4, 2])
2


In [ ]:
s = x.squeeze(0)
us = x.unsqueeze(0)
print(s)
print(s.ndim)
print(f"us: {us}")
print(f"us.shape: {us.shape}")
print(f"us.ndim: {us.ndim}")
print(f"us[0,0,0]: {us[0,0,0].item()}")

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
2
us: tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
us.shape: torch.Size([1, 4, 2])
us.ndim: 3
us[0]: 1


In [ ]:
lastus = x.unsqueeze(-1)
lastus

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]],

        [[7],
         [8]]])

In [ ]:
us[[0]] #how to visualize the effect of unsequeeze

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])

In [ ]:
import torch
x = torch.tensor([[1,2,3],[4,5,6]],
                 dtype = torch.float, requires_grad=True)
print(x)

f = x.pow(2).sum()
print(f"f is: {f}")

f.backward()
print(f"f.grad is: {x.grad}")

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
f is: 91.0
f.grad is: tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


End of Chapter 2

## Chapter 3 DL Development with PyTorch

In [ ]:
from torchvision.datasets import CIFAR10

train_data = CIFAR10(root = "./train/",
                     train=True,
                     download=True)

print(train_data)

100%|██████████| 170498071/170498071 [00:02<00:00, 75983933.78it/s]


Extracting ./train/cifar-10-python.tar.gz to ./train/
Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./train/
    Split: Train


In [ ]:
print(train_data.data.shape)

(50000, 32, 32, 3)


In [ ]:
print(train_data.data[0].shape)

(32, 32, 3)


In [ ]:
print(train_data.classes)

['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


In [ ]:
print(train_data.class_to_idx)

{'airplane': 0, 'automobile': 1, 'bird': 2, 'cat': 3, 'deer': 4, 'dog': 5, 'frog': 6, 'horse': 7, 'ship': 8, 'truck': 9}


In [ ]:
print(type(train_data[0]))

<class 'tuple'>


In [ ]:
print(len(train_data[0]))

2


In [ ]:
print(type(train_data))
data, label = train_data[0]
print(type(data))
print(data)


<class 'torchvision.datasets.cifar.CIFAR10'>
<class 'PIL.Image.Image'>
<PIL.Image.Image image mode=RGB size=32x32 at 0x787F4FB5D240>


In [ ]:
print(type(label))
print(label)
print(train_data.classes[label])

<class 'int'>
6
frog


In [ ]:
test_data = CIFAR10(root="./test/",
                    train=False,
                    download=True)

print(test_data)
print(test_data.data.shape)

100%|██████████| 170498071/170498071 [00:03<00:00, 55243187.44it/s]


Extracting ./test/cifar-10-python.tar.gz to ./test/
Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./test/
    Split: Test
(10000, 32, 32, 3)


In [ ]:
from torchvision import transforms

train_transforms = transforms.Compose([
    transforms.RandomCrop(32,padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(
        mean = (0.4914, 0.4822, 0.4465), #1
      std=(0.2023, 0.1994, 0.2010))])

train_data = CIFAR10(root="./train/",
                     train=True,
                     download=True,
                     transform = train_transforms)

Files already downloaded and verified


In [ ]:
print(train_data)

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./train/
    Split: Train
    StandardTransform
Transform: Compose(
               RandomCrop(size=(32, 32), padding=4)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=(0.4914, 0.4822, 0.4465), std=(0.2023, 0.1994, 0.201))
           )


In [ ]:
print(train_data.transforms)

StandardTransform
Transform: Compose(
               RandomCrop(size=(32, 32), padding=4)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=(0.4914, 0.4822, 0.4465), std=(0.2023, 0.1994, 0.201))
           )


In [ ]:
data, label = train_data[0]

print(type(data))

print(data.size())

print(data)

<class 'torch.Tensor'>
torch.Size([3, 32, 32])
tensor([[[-2.4291, -2.4291, -2.4291,  ..., -2.4291, -2.4291, -2.4291],
         [-2.4291, -2.4291, -2.4291,  ..., -2.4291, -2.4291, -2.4291],
         [-2.4291, -2.4291, -2.4291,  ..., -2.4291, -2.4291, -2.4291],
         ...,
         [ 1.1765,  1.7387,  0.8858,  ...,  1.1959,  1.4867, -2.4291],
         [-0.0253,  1.5642,  1.5061,  ...,  1.3122,  1.7581, -2.4291],
         [-1.3435,  0.9245,  1.1765,  ...,  1.4673,  1.8356, -2.4291]],

        [[-2.4183, -2.4183, -2.4183,  ..., -2.4183, -2.4183, -2.4183],
         [-2.4183, -2.4183, -2.4183,  ..., -2.4183, -2.4183, -2.4183],
         [-2.4183, -2.4183, -2.4183,  ..., -2.4183, -2.4183, -2.4183],
         ...,
         [ 0.6301,  1.1808,  0.1581,  ...,  0.1188,  0.6694, -2.4183],
         [-0.5892,  0.9841,  0.8661,  ...,  0.2564,  1.0038, -2.4183],
         [-1.8479,  0.4138,  0.6301,  ...,  0.5318,  1.1611, -2.4183]],

        [[-2.2214, -2.2214, -2.2214,  ..., -2.2214, -2.2214, -2.2214]

In [ ]:
test_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
            (0.4914, 0.4822, 0.4465),
            (0.2023, 0.1994, 0.2010)
    )
])

# test_data = torchvision.datasets.CIFAR10(
#     root="./test/",
#     train=False,
#     transform=test_transforms
# )

test_data = CIFAR10(
      root="./test/",
      train=False,
      transform=test_transforms)
print(test_data)

Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./test/
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.4914, 0.4822, 0.4465), std=(0.2023, 0.1994, 0.201))
           )


In [ ]:
import torch
trainloader = torch.utils.data.DataLoader(
    train_data,
    batch_size=16,
    shuffle=True
)

In [ ]:
data_batch, labels_batch = next(iter(trainloader))
print(data_batch.size())

print(labels_batch.size())

torch.Size([16, 3, 32, 32])
torch.Size([16])


In [ ]:
testloader = torch.utils.data.DataLoader(
    test_data,
    batch_size=16,
    shuffle=False  ## MyNote: shuffle the testset may messy test result
)

In [ ]:
torch.utils.data.DataLoader(
                dataset,
                batch_size=1,
                shuffle=False,
                sampler=None,
                batch_sampler=None,
                num_workers=0,
                collate_fn=None,
                pin_memory=False,
                drop_last=False,
                timeout=0,
                worker_init_fn=None,
                multiprocessing_context=None,
                generator=None)

NameError: name 'dataset' is not defined

In [ ]:
from torchvision import models

vgg16 = models.vgg16(pretrained=True)

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [ ]:
print(vgg16.classifier)

Sequential(
  (0): Linear(in_features=25088, out_features=4096, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=4096, out_features=4096, bias=True)
  (4): ReLU(inplace=True)
  (5): Dropout(p=0.5, inplace=False)
  (6): Linear(in_features=4096, out_features=1000, bias=True)
)


In [ ]:
import torch
waveglow = torch.hub.load(
    'nvidia/DeepLearningExamples:torchhub',
    'nvidia_waveglow'
)

Using cache found in /root/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub
/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:28: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")


In [ ]:
torch.hub.list('nvidia/DeepLearningExamples:torchhub')

Using cache found in /root/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub


['nvidia_convnets_processing_utils',
 'nvidia_efficientnet',
 'nvidia_efficientnet_b0',
 'nvidia_efficientnet_b4',
 'nvidia_efficientnet_widese_b0',
 'nvidia_efficientnet_widese_b4',
 'nvidia_fastpitch',
 'nvidia_gpunet',
 'nvidia_hifigan',
 'nvidia_resneXt',
 'nvidia_resnet50',
 'nvidia_resnext101_32x4d',
 'nvidia_se_resnext101_32x4d',
 'nvidia_ssd',
 'nvidia_ssd_processing_utils',
 'nvidia_tacotron2',
 'nvidia_textprocessing_utils',
 'nvidia_tft',
 'nvidia_tft_data_utils',
 'nvidia_tts_utils',
 'nvidia_waveglow']

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(2048,256)
        self.fc2 = nn.Linear(256,64)
        self.fc3 = nn.Linear(64,2)

    def forward(self, x):
        x = x.view(-1,2048) ### I don't know much about this effect, flat out the last dimension into 2048?
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x),dim=1)
        return x

In [ ]:
simplenet=SimpleNet()
print(simplenet)

SimpleNet(
  (fc1): Linear(in_features=2048, out_features=256, bias=True)
  (fc2): Linear(in_features=256, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)


In [ ]:
input = torch.rand(2048)
output = simplenet(input)

In [ ]:
output

tensor([[0.5208, 0.4792]], grad_fn=<SoftmaxBackward0>)

### Training
##### Fundamental training loop

In [ ]:
from torch import nn ##for building layers
import torch.nn.functional as F ## for forward function

class LeNet5(nn.Module):

    def __init__(self):
        super(LeNet5, self).__init__()
        self.conv1 = nn.Conv2d(3,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = x.view(-1,int(x.nelement()/x.shape[0]))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

device = ("cuda" if torch.cuda.is_available() else "cpu")
model = LeNet5().to(device=device)

In [ ]:
from torch import optim
from torch import nn ### why import again? he copied codes from other place?

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(),
                      lr=0.001,
                      momentum=0.9)

In [ ]:
N_EPOCHS = 10
for epoch in range(N_EPOCHS):

    epoch_loss = 0.0
    for inputs, labels in trainloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
    print("Epoch: {} Loss: {}".format(epoch, epoch_loss/len(trainloader)))

Epoch: 0 Loss: 1.9716070209884644
Epoch: 1 Loss: 1.6064669806289673
Epoch: 2 Loss: 1.4704029151153564
Epoch: 3 Loss: 1.3795007964897157
Epoch: 4 Loss: 1.3294903639793396
Epoch: 5 Loss: 1.2728908192920685
Epoch: 6 Loss: 1.2379712177085878
Epoch: 7 Loss: 1.2069621272277833
Epoch: 8 Loss: 1.177622131729126
Epoch: 9 Loss: 1.1521157801151276


In [ ]:
from torch.utils.data import random_split

train_set, val_set = random_split(
                      train_data,
                      [40000, 10000])

trainloader = torch.utils.data.DataLoader(
                    train_set,
                    batch_size=16,
                    shuffle=True)

valloader = torch.utils.data.DataLoader(
                    val_set,
                    batch_size=16,
                    shuffle=True)

print(len(trainloader))
# out: 2500
print(len(valloader))
# out: 625

In [ ]:
from torch import optim
from torch import nn

model = LeNet5().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(),
                      lr=0.001,
                      momentum=0.9)

In [ ]:
N_EPOCHS = 10
for epoch in range(N_EPOCHS):

    # Training
    train_loss = 0.0
    model.train() #1
    for inputs, labels in trainloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Validation
    val_loss = 0.0
    model.eval() #2
    for inputs, labels in valloader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        loss = criterion(outputs, labels)

        val_loss += loss.item()

    print(
      "Epoch: {} Train Loss: {} Val Loss: {}".format(
                  epoch,
                  train_loss/len(trainloader),
                  val_loss/len(valloader)))

In [ ]:
num_correct = 0.0
for x_test_batch, y_test_batch in testloader:
  model.eval() #1
  y_test_batch = y_test_batch.to(device)
  x_test_batch = x_test_batch.to(device)
  y_pred_batch = model(x_test_batch) #2
  _, predicted = torch.max(y_pred_batch, 1) #3
  num_correct += (predicted ==
    y_test_batch).float().sum() #4

accuracy = num_correct/(len(testloader) \
  *testloader.batch_size) #5

print(len(testloader), testloader.batch_size)
# out: 625 16

print("Test Accuracy: {}".format(accuracy))
# out: Test Accuracy: 0.6322000026702881

625 16
Test Accuracy: 0.09999999403953552
